builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - linux_arm
      - windows_amd64
    main: .
    ldflags:
      - -extldflags '-static'
      - -s -w -X main.version={{.Version}}

archives:
  - format: binary
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

kos:
  - base_image: alpine
    repository: ghcr.io/asmfreak/pages-server
    tags:
      - "v{{.Version}}"
      - latest
    bare: true
    sbom: none
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.license: "MIT"
      org.opencontainers.image.source: "https://github.com/ASMfreaK/pages-server.git"
